//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.15 at 03:32:50 PM CEST 
//


package eventcontentlist;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}eventcontent"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "eventcontent"
})
@XmlRootElement(name = "eventcontentlist")
public class Eventcontentlist {

    @XmlElement(required = true)
    protected Eventcontent eventcontent;

    /**
     * Gets the value of the eventcontent property.
     * 
     * @return
     *     possible object is
     *     {@link Eventcontent }
     *     
     */
    public Eventcontent getEventcontent() {
        return eventcontent;
    }

    /**
     * Sets the value of the eventcontent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Eventcontent }
     *     
     */
    public void setEventcontent(Eventcontent value) {
        this.eventcontent = value;
    }

}
