//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.15 at 03:32:50 PM CEST 
//


package eventcontentlist;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}aktuellerStand" minOccurs="0"/>
 *         &lt;element ref="{}tickerBeitrag" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="eventID" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "aktuellerStand",
    "tickerBeitrag"
})
@XmlRootElement(name = "eventcontent")
public class Eventcontent {

    protected AktuellerStand aktuellerStand;
    protected List<TickerBeitrag> tickerBeitrag;
    @XmlAttribute(name = "eventID")
    protected BigDecimal eventID;

    /**
     * Gets the value of the aktuellerStand property.
     * 
     * @return
     *     possible object is
     *     {@link AktuellerStand }
     *     
     */
    public AktuellerStand getAktuellerStand() {
        return aktuellerStand;
    }

    /**
     * Sets the value of the aktuellerStand property.
     * 
     * @param value
     *     allowed object is
     *     {@link AktuellerStand }
     *     
     */
    public void setAktuellerStand(AktuellerStand value) {
        this.aktuellerStand = value;
    }

    /**
     * Gets the value of the tickerBeitrag property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tickerBeitrag property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTickerBeitrag().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TickerBeitrag }
     * 
     * 
     */
    public List<TickerBeitrag> getTickerBeitrag() {
        if (tickerBeitrag == null) {
            tickerBeitrag = new ArrayList<TickerBeitrag>();
        }
        return this.tickerBeitrag;
    }

    /**
     * Gets the value of the eventID property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEventID() {
        return eventID;
    }

    /**
     * Sets the value of the eventID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEventID(BigDecimal value) {
        this.eventID = value;
    }

}
