//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.15 at 03:33:49 PM CEST 
//


package userlist;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}username"/>
 *         &lt;element ref="{}vorname"/>
 *         &lt;element ref="{}name"/>
 *         &lt;element ref="{}gender"/>
 *         &lt;element ref="{}geburtsdatum"/>
 *         &lt;element ref="{}land"/>
 *         &lt;element ref="{}stadt"/>
 *         &lt;element ref="{}anzEvents"/>
 *         &lt;element ref="{}beitraege"/>
 *         &lt;element ref="{}favoriten"/>
 *         &lt;element ref="{}folger"/>
 *       &lt;/sequence>
 *       &lt;attribute name="userID" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "username",
    "vorname",
    "name",
    "gender",
    "geburtsdatum",
    "land",
    "stadt",
    "anzEvents",
    "beitraege",
    "favoriten",
    "folger"
})
@XmlRootElement(name = "user")
public class User {

    @XmlElement(required = true)
    protected String username;
    @XmlElement(required = true)
    protected String vorname;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String gender;
    @XmlElement(required = true)
    protected XMLGregorianCalendar geburtsdatum;
    @XmlElement(required = true, defaultValue = "")
    protected String land;
    @XmlElement(required = true)
    protected String stadt;
    @XmlElement(required = true)
    protected BigDecimal anzEvents;
    @XmlElement(required = true)
    protected BigDecimal beitraege;
    @XmlElement(required = true)
    protected Favoriten favoriten;
    @XmlElement(required = true)
    protected Folger folger;
    @XmlAttribute(name = "userID")
    protected BigDecimal userID;

    /**
     * Gets the value of the username property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the value of the username property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsername(String value) {
        this.username = value;
    }

    /**
     * Gets the value of the vorname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVorname() {
        return vorname;
    }

    /**
     * Sets the value of the vorname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVorname(String value) {
        this.vorname = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGender(String value) {
        this.gender = value;
    }

    /**
     * Gets the value of the geburtsdatum property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getGeburtsdatum() {
        return geburtsdatum;
    }

    /**
     * Sets the value of the geburtsdatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setGeburtsdatum(XMLGregorianCalendar value) {
        this.geburtsdatum = value;
    }

    /**
     * Gets the value of the land property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLand() {
        return land;
    }

    /**
     * Sets the value of the land property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLand(String value) {
        this.land = value;
    }

    /**
     * Gets the value of the stadt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStadt() {
        return stadt;
    }

    /**
     * Sets the value of the stadt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStadt(String value) {
        this.stadt = value;
    }

    /**
     * Gets the value of the anzEvents property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAnzEvents() {
        return anzEvents;
    }

    /**
     * Sets the value of the anzEvents property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAnzEvents(BigDecimal value) {
        this.anzEvents = value;
    }

    /**
     * Gets the value of the beitraege property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBeitraege() {
        return beitraege;
    }

    /**
     * Sets the value of the beitraege property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBeitraege(BigDecimal value) {
        this.beitraege = value;
    }

    /**
     * Gets the value of the favoriten property.
     * 
     * @return
     *     possible object is
     *     {@link Favoriten }
     *     
     */
    public Favoriten getFavoriten() {
        return favoriten;
    }

    /**
     * Sets the value of the favoriten property.
     * 
     * @param value
     *     allowed object is
     *     {@link Favoriten }
     *     
     */
    public void setFavoriten(Favoriten value) {
        this.favoriten = value;
    }

    /**
     * Gets the value of the folger property.
     * 
     * @return
     *     possible object is
     *     {@link Folger }
     *     
     */
    public Folger getFolger() {
        return folger;
    }

    /**
     * Sets the value of the folger property.
     * 
     * @param value
     *     allowed object is
     *     {@link Folger }
     *     
     */
    public void setFolger(Folger value) {
        this.folger = value;
    }

    /**
     * Gets the value of the userID property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUserID() {
        return userID;
    }

    /**
     * Sets the value of the userID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUserID(BigDecimal value) {
        this.userID = value;
    }

}
