//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.15 at 03:33:27 PM CEST 
//


package eventlist;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.Duration;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}eventname"/>
 *         &lt;element ref="{}eventbeschreibung"/>
 *         &lt;element ref="{}username"/>
 *         &lt;element ref="{}eventtyp"/>
 *         &lt;element name="eventstart" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="eventdauer" type="{http://www.w3.org/2001/XMLSchema}duration"/>
 *         &lt;element ref="{}eventbewertung"/>
 *       &lt;/sequence>
 *       &lt;attribute name="userID" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="eventID" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "eventname",
    "eventbeschreibung",
    "username",
    "eventtyp",
    "eventstart",
    "eventdauer",
    "eventbewertung"
})
@XmlRootElement(name = "event")
public class Event {

    @XmlElement(required = true)
    protected String eventname;
    @XmlElement(required = true)
    protected String eventbeschreibung;
    @XmlElement(required = true)
    protected String username;
    @XmlElement(required = true, defaultValue = "Football")
    protected String eventtyp;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar eventstart;
    @XmlElement(required = true)
    protected Duration eventdauer;
    protected byte eventbewertung;
    @XmlAttribute(name = "userID")
    protected BigDecimal userID;
    @XmlAttribute(name = "eventID")
    protected BigDecimal eventID;

    /**
     * Gets the value of the eventname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventname() {
        return eventname;
    }

    /**
     * Sets the value of the eventname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventname(String value) {
        this.eventname = value;
    }

    /**
     * Gets the value of the eventbeschreibung property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventbeschreibung() {
        return eventbeschreibung;
    }

    /**
     * Sets the value of the eventbeschreibung property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventbeschreibung(String value) {
        this.eventbeschreibung = value;
    }

    /**
     * Gets the value of the username property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the value of the username property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsername(String value) {
        this.username = value;
    }

    /**
     * Gets the value of the eventtyp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventtyp() {
        return eventtyp;
    }

    /**
     * Sets the value of the eventtyp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventtyp(String value) {
        this.eventtyp = value;
    }

    /**
     * Gets the value of the eventstart property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEventstart() {
        return eventstart;
    }

    /**
     * Sets the value of the eventstart property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEventstart(XMLGregorianCalendar value) {
        this.eventstart = value;
    }

    /**
     * Gets the value of the eventdauer property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getEventdauer() {
        return eventdauer;
    }

    /**
     * Sets the value of the eventdauer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setEventdauer(Duration value) {
        this.eventdauer = value;
    }

    /**
     * Gets the value of the eventbewertung property.
     * 
     */
    public byte getEventbewertung() {
        return eventbewertung;
    }

    /**
     * Sets the value of the eventbewertung property.
     * 
     */
    public void setEventbewertung(byte value) {
        this.eventbewertung = value;
    }

    /**
     * Gets the value of the userID property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUserID() {
        return userID;
    }

    /**
     * Sets the value of the userID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUserID(BigDecimal value) {
        this.userID = value;
    }

    /**
     * Gets the value of the eventID property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEventID() {
        return eventID;
    }

    /**
     * Sets the value of the eventID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEventID(BigDecimal value) {
        this.eventID = value;
    }

}
